export interface AreaData {
  slug: string;
  name: string;
  city: string;
  citySlug: string;
  kommunenummer: string;
  population: string;
  avgSqmPrice: number;
  avgSqmPriceYoY: number;
  priceSegment: "Lavt" | "Middels" | "Høyt" | "Svært høyt";
  transitScore: "Utmerket" | "Godt" | "Middels" | "Begrenset";
  topStreets: string[];
  metaTitle: string;
  metaDescription: string;
  heroHeading: string;
  heroSubheading: string;
  introText: string;
  transitText: string;
  faq: Array<{ q: string; a: string }>;
}

export const areas: Record<string, AreaData> = {
  // ── Oslo bydeler ──
  frogner: {
    slug: "frogner",
    name: "Frogner",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "60 000",
    avgSqmPrice: 151900,
    avgSqmPriceYoY: 5.2,
    priceSegment: "Svært høyt",
    transitScore: "Utmerket",
    topStreets: ["Bygdøy allé", "Frognerveien", "Drammensveien", "Kirkeveien"],
    metaTitle: "Frogner Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Frogner i Oslo. Gjennomsnittlig kvadratmeterpris: 151 900 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Frogner — Oslos dyreste bydel",
    heroSubheading: "Ambassadestrøk, villa og art nouveau-bygg langs fjorden",
    introText: "Frogner er blant Norges mest attraktive boområder. Bydelen strekker seg fra Frognerparken ned mot Bygdøy og kjennetegnes av store leiligheter i klassiske murgårder, ambassader og strandlinje. Kvadratmeterprisen er blant de høyeste i landet.",
    transitText: "Frogner er svært godt dekket av kollektivtransport. T-bane linje 1 (Frognerseteren), trikkelinjene 12 og 19 samt en rekke busslinjer gir rask tilgang til Oslo S og Nationaltheatret.",
    faq: [
      { q: "Hva er gjennomsnittsprisen per m² i Frogner?", a: "Gjennomsnittlig kvadratmeterpris i Frogner er ca. 151 900 kr/m² (SSB, siste kvartal 2024). Dette er blant de høyeste i landet." },
      { q: "Er Frogner et godt sted å bo?", a: "Frogner scorer høyt på nærhet til parker, restauranter, kafeer og kulturtilbud. Skoletilbudet er godt, og bydelen er trygg med lav kriminalitetsrate." },
      { q: "Hvilke T-banelinjer dekker Frogner?", a: "Linje 1 (Frognerseteren–Bergkrystallen) har stasjoner på Nationaltheatret og Majorstuen, begge innen gangavstand fra de fleste adresser i Frogner." },
    ],
  },
  grunerløkka: {
    slug: "grunerlokka",
    name: "Grünerløkka",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "55 000",
    avgSqmPrice: 112400,
    avgSqmPriceYoY: 6.1,
    priceSegment: "Høyt",
    transitScore: "Utmerket",
    topStreets: ["Thorvald Meyers gate", "Markveien", "Grüners gate", "Olaf Ryes plass"],
    metaTitle: "Grünerløkka Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Grünerløkka i Oslo. Gjennomsnittlig kvadratmeterpris: 112 400 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Grünerløkka — Kultur, kaffe og mangfold",
    heroSubheading: "Oslos hippe bydel med trikk, elvepark og streetfood",
    introText: "Grünerløkka er en av Oslos mest levende bydeler med et rikt uteliv, uavhengige butikker og Akerselva som grønn ryggrad. Boligmassen domineres av mursteinsbygg fra 1880–1920-tallet, nå omgjort til attraktive leiligheter.",
    transitText: "Trikkelinjene 11, 12 og 18 løper gjennom bydelen og gir rask tilgang til sentrum og Majorstuen. Busslinjer 37 og 54 dekker østre del.",
    faq: [
      { q: "Hva er prisen per m² på Grünerløkka?", a: "Gjennomsnittlig kvadratmeterpris er ca. 112 400 kr/m², opp 6,1 % siste år. Bydelen har hatt sterk prisvekst de siste 10 årene." },
      { q: "Er Grünerløkka trygt?", a: "Grünerløkka har moderat kriminalitetsrate sammenlignet med Oslo sentrum. Det har blitt tryggere de siste årene i takt med gentrifiseringen." },
      { q: "Finnes det familieleiligheter på Grünerløkka?", a: "Ja, særlig i randsonene mot Sinsen og Sofienberg finner man større leiligheter. Olaf Ryes plass-området er populært blant barnefamilier." },
    ],
  },
  // Alias for URL slug
  grunerlokka: {
    slug: "grunerlokka",
    name: "Grünerløkka",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "55 000",
    avgSqmPrice: 112400,
    avgSqmPriceYoY: 6.1,
    priceSegment: "Høyt",
    transitScore: "Utmerket",
    topStreets: ["Thorvald Meyers gate", "Markveien", "Grüners gate", "Olaf Ryes plass"],
    metaTitle: "Grünerløkka Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Grünerløkka i Oslo. Gjennomsnittlig kvadratmeterpris: 112 400 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Grünerløkka — Kultur, kaffe og mangfold",
    heroSubheading: "Oslos hippe bydel med trikk, elvepark og streetfood",
    introText: "Grünerløkka er en av Oslos mest levende bydeler med et rikt uteliv, uavhengige butikker og Akerselva som grønn ryggrad. Boligmassen domineres av mursteinsbygg fra 1880–1920-tallet, nå omgjort til attraktive leiligheter.",
    transitText: "Trikkelinjene 11, 12 og 18 løper gjennom bydelen og gir rask tilgang til sentrum og Majorstuen. Busslinjer 37 og 54 dekker østre del.",
    faq: [
      { q: "Hva er prisen per m² på Grünerløkka?", a: "Gjennomsnittlig kvadratmeterpris er ca. 112 400 kr/m², opp 6,1 % siste år." },
      { q: "Er Grünerløkka trygt?", a: "Grünerløkka har moderat kriminalitetsrate sammenlignet med Oslo sentrum. Det har blitt tryggere de siste årene." },
      { q: "Finnes det familieleiligheter på Grünerløkka?", a: "Ja, særlig i randsonene mot Sinsen og Sofienberg finner man større leiligheter." },
    ],
  },
  majorstuen: {
    slug: "majorstuen",
    name: "Majorstuen",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "28 000",
    avgSqmPrice: 134200,
    avgSqmPriceYoY: 4.8,
    priceSegment: "Svært høyt",
    transitScore: "Utmerket",
    topStreets: ["Bogstadveien", "Vibes gate", "Sørkedalsveien", "Kirkeveien"],
    metaTitle: "Majorstuen Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Majorstuen i Oslo. Gjennomsnittlig kvadratmeterpris: 134 200 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Majorstuen — Shoppegaten og T-baneknuten",
    heroSubheading: "Vest-Oslos pulserende knutepunkt med alt innen gangavstand",
    introText: "Majorstuen er et av Oslos viktigste kollektivknutepunkter og shoppingstrøk. Bogstadveien er en av Norges mest populære handlegater. Boligmassen er variert — fra klassiske murgårder til nyere leiligheter.",
    transitText: "Majorstuen stasjon er knutepunkt for T-banelinje 1, 2, 3 og 6, samt trikkelinjene 11 og 12. Det er svært sjelden man venter mer enn 3 minutter på neste avgang.",
    faq: [
      { q: "Hva er kvadratmeterprisen på Majorstuen?", a: "Gjennomsnittlig kvadratmeterpris er ca. 134 200 kr/m², noe lavere enn Frogner men fortsatt i øverste sjikt i Oslo." },
      { q: "Hvilket kollektivtilbud finnes på Majorstuen?", a: "Majorstuen er et av Oslos beste kollektivknutepunkter — 4 T-banelinjer og 2 trikkelinjer. Reisetid til Oslo S: ~8 minutter." },
      { q: "Passer Majorstuen for barnefamilier?", a: "Ja — gode skoler, Frognerparken i umiddelbar nærhet, lite gjennomgangstrafikk i boliggatene og høy trygghet." },
    ],
  },
  // ── Bergen bydeler ──
  "nordnes": {
    slug: "nordnes",
    name: "Nordnes",
    city: "Bergen",
    citySlug: "bergen",
    kommunenummer: "4601",
    population: "9 000",
    avgSqmPrice: 72400,
    avgSqmPriceYoY: 4.1,
    priceSegment: "Høyt",
    transitScore: "Godt",
    topStreets: ["Nordnesparken", "Nedre Korskirkeallmenning", "Nøstegaten"],
    metaTitle: "Nordnes Bergen — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Nordnes i Bergen. Gjennomsnittlig kvadratmeterpris: 72 400 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Nordnes — Bergen ut mot Byfjorden",
    heroSubheading: "Tett og sjarmerende trebyhusbebyggelse med fjordutsikt",
    introText: "Nordnes er en halvøy vest i Bergen sentrum med en unik blanding av sjøhus, trebyer og det populære Nordnesparken med sjøbadet. Et av Bergens mest ettertraktede boligområder.",
    transitText: "Busslinjer fra Bergen sentrum dekker Nordnes. Bysykkel er populært. Gange til Bryggen: ~10 minutter.",
    faq: [
      { q: "Hva er boligprisene på Nordnes?", a: "Gjennomsnittlig kvadratmeterpris er ca. 72 400 kr/m². Prisene er høye sammenlignet med Bergen generelt, men lave sett mot Oslo." },
      { q: "Er det lett å komme seg kollektivt fra Nordnes?", a: "Buss er det primære alternativet. Bybanen går ikke til Nordnes, men til sentrum er det kort sykkel- eller gangtid." },
    ],
  },
  // ── Bergen bydeler (flere) ──
  fana: {
    slug: "fana",
    name: "Fana",
    city: "Bergen",
    citySlug: "bergen",
    kommunenummer: "4601",
    population: "40 000",
    avgSqmPrice: 52300,
    avgSqmPriceYoY: 3.8,
    priceSegment: "Middels",
    transitScore: "Godt",
    topStreets: ["Fanaveien", "Nesttunveien", "Skjoldveien"],
    metaTitle: "Fana Bergen — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Fana i Bergen. Gjennomsnittlig kvadratmeterpris: 52 300 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Fana — Familievennlig med Bybane-tilgang",
    heroSubheading: "Bergens største bydel med eneboligerparadis og rask vei til sentrum",
    introText: "Fana ligger sør i Bergen og er en av byens mest familievennlige bydeler. Området byr på en blanding av eneboliger, rekkehus og nyere leiligheter, med god tilgang til Bybanen fra Nesttun og Fantoft stasjon.",
    transitText: "Bybanen har flere holdeplasser i Fana, inkludert Nesttun og Fantoft. Reisetid til Bergen sentrum er ca. 15 minutter. I tillegg finnes flere busslinjer.",
    faq: [
      { q: "Hva er boligprisene i Fana?", a: "Gjennomsnittlig kvadratmeterpris i Fana er ca. 52 300 kr/m². Dette er moderat sammenlignet med Bergen sentrum." },
      { q: "Er Fana godt for barnefamilier?", a: "Ja — Fana har flere gode skoler, idrettsanlegg og nærhet til Fanafjorden og Lysekloster. Området er populært blant barnefamilier." },
      { q: "Hvordan er kollektivtilbudet i Fana?", a: "Bybanen gir rask forbindelse til sentrum. I tillegg er det et godt utbygd bussnett i hele bydelen." },
    ],
  },
  sandviken: {
    slug: "sandviken",
    name: "Sandviken",
    city: "Bergen",
    citySlug: "bergen",
    kommunenummer: "4601",
    population: "15 000",
    avgSqmPrice: 58700,
    avgSqmPriceYoY: 4.5,
    priceSegment: "Middels",
    transitScore: "Godt",
    topStreets: ["Sandviksveien", "Nye Sandviksveien", "Sjøgaten"],
    metaTitle: "Sandviken Bergen — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Sandviken i Bergen. Gjennomsnittlig kvadratmeterpris: 58 700 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Sandviken — Bergen ved sjøen",
    heroSubheading: "Historisk sjøfartsbydel nord for Bryggen med stigende attraktivitet",
    introText: "Sandviken er en av Bergens eldste bydeler, beliggende nord for Bryggen langs Byfjorden. Området kjennetegnes av sjøhus, trange smau og en blanding av eldre og nyere boliger. Sandviken har gjennomgått stor utvikling de siste årene.",
    transitText: "Buss er primærtransporten i Sandviken. Flere linjer gir rask forbindelse til Bergen sentrum. Gange til Bryggen: ~15 minutter.",
    faq: [
      { q: "Hva er boligprisene i Sandviken?", a: "Gjennomsnittlig kvadratmeterpris er ca. 58 700 kr/m². Prisene har steget jevnt de siste årene." },
      { q: "Er Sandviken et trygt område?", a: "Ja, Sandviken er generelt et trygt og rolig boligområde med et aktivt lokalmiljø." },
    ],
  },
  // ── Trondheim bydeler ──
  bakklandet: {
    slug: "bakklandet",
    name: "Bakklandet",
    city: "Trondheim",
    citySlug: "trondheim",
    kommunenummer: "5001",
    population: "4 000",
    avgSqmPrice: 68200,
    avgSqmPriceYoY: 5.0,
    priceSegment: "Høyt",
    transitScore: "Godt",
    topStreets: ["Nedre Bakklandet", "Øvre Bakklandet", "Gamle Bybro"],
    metaTitle: "Bakklandet Trondheim — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Bakklandet i Trondheim. Gjennomsnittlig kvadratmeterpris: 68 200 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Bakklandet — Trondheims sjarmerende perle",
    heroSubheading: "Trehusbyen langs Nidelva med kafeer, gallerier og brosteinsgater",
    introText: "Bakklandet er et av Trondheims mest populære og sjarmerende områder. De fargerike trehusene langs Nidelva, brosteinsgatene og de mange kafeene gjør det til et unikt boligstrøk. Området er lite med høy etterspørsel.",
    transitText: "Bakklandet ligger i gangavstand fra Trondheim sentrum og Nidarosdomen. Buss og trikk (Gråkallbanen) er tilgjengelig i nærområdet.",
    faq: [
      { q: "Hva er boligprisene på Bakklandet?", a: "Gjennomsnittlig kvadratmeterpris er ca. 68 200 kr/m². Prisene er høye for Trondheim, drevet av stor etterspørsel og begrenset tilbud." },
      { q: "Er Bakklandet godt å bo i?", a: "Ja — det er et av Trondheims mest attraktive strøk med kort vei til sentrum, universitet og grøntarealer langs Nidelva." },
    ],
  },
  lade: {
    slug: "lade",
    name: "Lade",
    city: "Trondheim",
    citySlug: "trondheim",
    kommunenummer: "5001",
    population: "12 000",
    avgSqmPrice: 55100,
    avgSqmPriceYoY: 4.2,
    priceSegment: "Middels",
    transitScore: "Godt",
    topStreets: ["Ladeveien", "Haakon VIIs gate", "Leangen allé"],
    metaTitle: "Lade Trondheim — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Lade i Trondheim. Gjennomsnittlig kvadratmeterpris: 55 100 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Lade — Sjøfront og moderne boliger",
    heroSubheading: "Trondheims nye bydel med strandpromenade og kort vei til sentrum",
    introText: "Lade er et område i sterk utvikling øst for Trondheim sentrum. Bydelen har fått stor tilflytting takket være nye leilighetsprosjekter, sjøfronten og nærhet til Leangen idrettssenter. Blanding av eldre villaer og moderne leiligheter.",
    transitText: "Buss gir rask forbindelse til sentrum (ca. 10 minutter). Ladeveien er en hovedferdselsåre med hyppige avganger.",
    faq: [
      { q: "Hva er boligprisene på Lade?", a: "Gjennomsnittlig kvadratmeterpris er ca. 55 100 kr/m², noe under Trondheim sentrum men i rask vekst." },
      { q: "Hva finnes av fasiliteter på Lade?", a: "Leangen idrettsanlegg, strandpromenaden, flere butikker og restauranter. Kort vei til Lade Arena handlesenter." },
    ],
  },
  moholt: {
    slug: "moholt",
    name: "Moholt",
    city: "Trondheim",
    citySlug: "trondheim",
    kommunenummer: "5001",
    population: "8 000",
    avgSqmPrice: 48900,
    avgSqmPriceYoY: 3.6,
    priceSegment: "Middels",
    transitScore: "Godt",
    topStreets: ["Moholt allé", "Jonsvannsveien", "Steinanveien"],
    metaTitle: "Moholt Trondheim — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser, kollektivtransport og nabolagsdata for Moholt i Trondheim. Gjennomsnittlig kvadratmeterpris: 48 900 kr/m². Se full analyse på Verdikart.",
    heroHeading: "Moholt — Studentby og familiestrøk",
    heroSubheading: "Nær NTNU med rimelige boliger og godt kollektivtilbud",
    introText: "Moholt er kjent for Norges største studentby, Moholt studentby, og er et populært boligområde for både studenter og familier. Bydelen har rimelige priser sammenlignet med sentrum, og god tilgang til NTNU Gløshaugen.",
    transitText: "Metrobussen (linje 1) stopper på Moholt og gir reisetid til sentrum på ca. 12 minutter. Flere busslinjer supplerer tilbudet.",
    faq: [
      { q: "Hva er boligprisene på Moholt?", a: "Gjennomsnittlig kvadratmeterpris er ca. 48 900 kr/m² — blant de rimeligste i sentrumsnære Trondheim." },
      { q: "Passer Moholt for studenter?", a: "Absolutt — Moholt studentby huser ca. 2 300 studenter, og NTNU Gløshaugen er 10 minutters gange unna." },
    ],
  },
  // ── Oslo nabolag (utvidet) ──
  "st-hanshaugen": {
    slug: "st-hanshaugen",
    name: "St. Hanshaugen",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "38 000",
    avgSqmPrice: 110200,
    avgSqmPriceYoY: 4.8,
    priceSegment: "Høyt",
    transitScore: "Utmerket",
    topStreets: ["Ullevålsveien", "St. Olavs gate", "Pilestredet"],
    metaTitle: "St. Hanshaugen Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for St. Hanshaugen i Oslo. Gjennomsnittlig kvadratmeterpris: 110 200 kr/m².",
    heroHeading: "St. Hanshaugen — Grønt hjerte i Oslo",
    heroSubheading: "Parken, T-banen og det beste av indre vest",
    introText: "St. Hanshaugen er en av Oslos mest attraktive bydeler for unge profesjonelle og familier. Med St. Hanshaugen park i sentrum, tett bebyggelse av mursteinsbygg og enkel adgang til T-bane gir bydelen det beste av byliv og ro.",
    transitText: "Stortinget og Nationaltheatret T-banestasjoner er innen gangavstand. Trikkelinjene 17 og 18 løper langs Ullevålsveien. Buss 37 og 30 dekker Pilestredet-korridoren.",
    faq: [
      { q: "Hva koster bolig på St. Hanshaugen?", a: "Gjennomsnittlig kvadratmeterpris er ca. 110 200 kr/m². Prisene har steget 4,8 % siste år." },
      { q: "Er St. Hanshaugen trygt?", a: "Ja, bydelen er trygg med lav kriminalitet og et aktivt nabolagsmiljø rundt parken." },
      { q: "Hvilken T-bane betjener St. Hanshaugen?", a: "Nationaltheatret og Stortinget er nærmeste stasjoner, begge innen 10 minutters gange." },
    ],
  },
  sagene: {
    slug: "sagene",
    name: "Sagene",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "45 000",
    avgSqmPrice: 98700,
    avgSqmPriceYoY: 5.5,
    priceSegment: "Høyt",
    transitScore: "Godt",
    topStreets: ["Sandakerveien", "Vogts gate", "Torshov"],
    metaTitle: "Sagene Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Sagene i Oslo. Gjennomsnittlig kvadratmeterpris: 98 700 kr/m².",
    heroHeading: "Sagene — Arbeiderklasseromantikk møter moderne byliv",
    heroSubheading: "Torshov, Årvoll og Akerselva langs elvebredden",
    introText: "Sagene har de siste ti årene gjennomgått en sterk gentrifisering. Gamle industribygg langs Akerselva er blitt til leiligheter og kontorer, og Torshov er blitt et trendy nabolag med kafeer og restauranter. Prisen er fortsatt lavere enn indre vest.",
    transitText: "Trikkelinje 11 og 12 kobler Sagene til sentrum og Majorstuen. T-bane via Storo (linje 4 og 5) gir direkte forbindelse til Nationaltheatret.",
    faq: [
      { q: "Hva er prisen per m² i Sagene?", a: "Gjennomsnittlig kvadratmeterpris er ca. 98 700 kr/m², opp 5,5 % siste år." },
      { q: "Er Sagene et godt sted å bo?", a: "Sagene er populært blant unge og barnefamilier. Akerselva-korridoren og Torshov park gir gode rekreasjonstilbud." },
      { q: "Hvilken T-bane betjener Sagene?", a: "Storo T-banestasjon (linje 4/5) er nærmeste stasjon. Trikkelinjene 11, 12, 18 dekker Sagene-aksen." },
    ],
  },
  gronland: {
    slug: "gronland",
    name: "Grønland",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "18 000",
    avgSqmPrice: 89400,
    avgSqmPriceYoY: 7.2,
    priceSegment: "Middels",
    transitScore: "Utmerket",
    topStreets: ["Grønlandsleiret", "Tøyengata", "Schweigaards gate"],
    metaTitle: "Grønland Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Grønland i Oslo. Gjennomsnittlig kvadratmeterpris: 89 400 kr/m². Høy prisvekst og central beliggenhet.",
    heroHeading: "Grønland — Oslos mest mangfoldige nabolag",
    heroSubheading: "Sentralt, billig og i rask forandring",
    introText: "Grønland er Oslos mest mangfoldige nabolag med en unik blanding av kulturer, markeder og restauranter. Bydelen har hatt kraftig prisvekst de siste årene ettersom unge par oppdager den sentrale beliggenheten og de relativt lave prisene.",
    transitText: "Grønland T-banestasjon (alle linjer) og Bryn/Ensjø gir svært god kollektivdekning. Jernbanetorget er 5 minutters gange.",
    faq: [
      { q: "Hva koster bolig på Grønland?", a: "Gjennomsnittlig kvadratmeterpris er ca. 89 400 kr/m², med en sterk prisvekst på 7,2 % siste år." },
      { q: "Er Grønland trygt?", a: "Grønland har hatt utfordringer, men bydelen har blitt vesentlig tryggere de siste 5 årene. Politiet er synlig og nabonettverk aktive." },
      { q: "Hvilken T-bane betjener Grønland?", a: "Grønland T-banestasjon (alle 5 linjer) er sentralt i bydelen." },
    ],
  },
  toyen: {
    slug: "toyen",
    name: "Tøyen",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "16 000",
    avgSqmPrice: 87300,
    avgSqmPriceYoY: 7.8,
    priceSegment: "Middels",
    transitScore: "Utmerket",
    topStreets: ["Tøyengata", "Kolstadgata", "Herslebs gate"],
    metaTitle: "Tøyen Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Tøyen i Oslo. Gjennomsnittlig kvadratmeterpris: 87 300 kr/m². En bydel i rask forandring.",
    heroHeading: "Tøyen — Fra slitasjespor til vekstmotor",
    heroSubheading: "Munchmuseet, Botanisk hage og Oslos sterkeste prisoppgang",
    introText: "Tøyen er Oslos mest spennende nabolag akkurat nå. Bydelen har gjennomgått en massiv transformasjon siden Tøyen-løftet (2015), med nye barnehager, lekeplasser og kulturhuset Deichmanske. Prisoppgangen på 7,8 % siste år er den sterkeste i Oslo.",
    transitText: "Tøyen T-banestasjon (linje 2, 3, 4) gir rask tilgang til Oslo S og sentrum. Ruter buss 20 og 23 dekker Tøyengata-aksen.",
    faq: [
      { q: "Hva er prisen per m² på Tøyen?", a: "Gjennomsnittlig kvadratmeterpris er ca. 87 300 kr/m², med en vekst på 7,8 % siste år — høyest i Oslo." },
      { q: "Er Tøyen et trygt nabolag?", a: "Tøyen har forandret seg mye. Etter Tøyen-løftet og investeringene er trygghetsfølelsen vesentlig bedre. Fortsatt noe høyere kriminalitet enn vestkanten." },
      { q: "Hva er Tøyen-løftet?", a: "Tøyen-løftet er en bydelssatsing fra 2013–2020 med over 300 mill. kr investert i barnehager, skoler, park og kulturhus for å løfte bydelen." },
    ],
  },
  sofienberg: {
    slug: "sofienberg",
    name: "Sofienberg",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "14 000",
    avgSqmPrice: 103200,
    avgSqmPriceYoY: 5.9,
    priceSegment: "Høyt",
    transitScore: "Utmerket",
    topStreets: ["Sofienberggata", "Helgesens gate", "Sannergata"],
    metaTitle: "Sofienberg Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Sofienberg i Oslo. Gjennomsnittlig kvadratmeterpris: 103 200 kr/m².",
    heroHeading: "Sofienberg — Stille gater mellom Grünerløkka og Grønland",
    heroSubheading: "Bokhandlere, kafeer og mursteinsbygg langs parken",
    introText: "Sofienberg er et rolig nabolag mellom det travle Grünerløkka og det mer urbane Grønland. Sofienberg park er bydelens grønne sentrum, og gaten langs parken er populær blant barnefamilier.",
    transitText: "Trikkelinjene 11, 12 og 13 er innen gangavstand. Grønland T-bane nås på 5 minutter.",
    faq: [
      { q: "Hva koster bolig i Sofienberg?", a: "Gjennomsnittlig kvadratmeterpris er ca. 103 200 kr/m²." },
      { q: "Er Sofienberg trygt?", a: "Sofienberg er et rolig nabolag med god trygghetsfølelse, spesielt rundt parken." },
      { q: "Hva er nærmeste T-bane til Sofienberg?", a: "Grønland T-banestasjon er nærmeste, ca. 8 minutters gange." },
    ],
  },
  bislett: {
    slug: "bislett",
    name: "Bislett",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "11 000",
    avgSqmPrice: 108900,
    avgSqmPriceYoY: 5.1,
    priceSegment: "Høyt",
    transitScore: "Utmerket",
    topStreets: ["Pilestredet", "Josefines gate", "Thereses gate"],
    metaTitle: "Bislett Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Bislett i Oslo. Gjennomsnittlig kvadratmeterpris: 108 900 kr/m².",
    heroHeading: "Bislett — Klassisk Oslo-vest med kultstatus",
    heroSubheading: "Stadion, pølser og Norges tettest befolkede nabolag",
    introText: "Bislett er kjent for Bislett Stadion og det ikoniske nabolagslivet rundt. Nabolaget kjennetegnes av tett bebyggelse med mursteinsbygg fra tidlig 1900-tall, mange kafeer og nærbutikker og god T-baneforbindelse.",
    transitText: "Nationaltheatret T-banestasjon er nærmeste (linje 1, 2, 3, 4, 5). Trikkelinje 12 og 19 betjener Pilestredet/Briskebyveien.",
    faq: [
      { q: "Hva koster bolig på Bislett?", a: "Gjennomsnittlig kvadratmeterpris er ca. 108 900 kr/m²." },
      { q: "Hva er nærmeste T-bane til Bislett?", a: "Nationaltheatret stasjon er 7–10 minutters gange fra mesteparten av Bislett." },
      { q: "Er Bislett et godt nabolag?", a: "Bislett er svært populært — sentralt, levende og med sterk naboidentitet." },
    ],
  },
  skillebek: {
    slug: "skillebek",
    name: "Skillebekk",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "8 000",
    avgSqmPrice: 134600,
    avgSqmPriceYoY: 4.7,
    priceSegment: "Svært høyt",
    transitScore: "Utmerket",
    topStreets: ["Bygdøy allé", "Inkognitogata", "Riddervolds gate"],
    metaTitle: "Skillebekk Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Skillebekk i Oslo. Gjennomsnittlig kvadratmeterpris: 134 600 kr/m².",
    heroHeading: "Skillebekk — Stille og eksklusivt mellom Frogner og sentrum",
    heroSubheading: "Ambassadestrøk, Bygdøy allé og lav gjennomfartstrafikk",
    introText: "Skillebekk er et eksklusivt nabolag som mange ikke har hørt om — tucked between Frogner og sentrum, med lav trafikk og høye priser. Adressene langs Bygdøy allé er blant Oslos mest ettertraktede.",
    transitText: "Nationaltheatret T-bane og trikkelinjene 12 og 13 er innen 8 minutters gange. Ruter buss 30 betjener Bygdøy allé direkte.",
    faq: [
      { q: "Hva koster bolig på Skillebekk?", a: "Gjennomsnittlig kvadratmeterpris er ca. 134 600 kr/m² — blant Oslos dyreste." },
      { q: "Er Skillebekk trygt?", a: "Skillebekk er et av Oslos tryggeste nabolag med svært lav kriminalitetsrate." },
      { q: "Hvilken T-bane er nærmest Skillebekk?", a: "Nationaltheatret er nærmeste T-banestasjon, ca. 8–10 minutters gange." },
    ],
  },
  "aker-brygge": {
    slug: "aker-brygge",
    name: "Aker Brygge",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "4 000",
    avgSqmPrice: 148200,
    avgSqmPriceYoY: 4.3,
    priceSegment: "Svært høyt",
    transitScore: "Utmerket",
    topStreets: ["Bryggegata", "Stranden", "Tjuvholmen allé"],
    metaTitle: "Aker Brygge Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Aker Brygge i Oslo. Gjennomsnittlig kvadratmeterpris: 148 200 kr/m². Fjordutsikt og urbant luksusliv.",
    heroHeading: "Aker Brygge — Fjordutsikt og urban luksus",
    heroSubheading: "Norges dyreste nabolag per kvadratmeter",
    introText: "Aker Brygge og Tjuvholmen er Norges fremste urban luxury-nabolag. Med direkte sjøfront, ferge til Bygdøy og Aker Brygge-kjøpesenteret i nærheten, er dette destinasjonen for de som vil ha det beste av fjord og by.",
    transitText: "Nationaltheatret T-bane er 10 minutters gange. Aker Brygge ferjekai kobler til Bygdøy og Nesodden. Trikkelinje 12 langs Aker Brygge.",
    faq: [
      { q: "Hva koster bolig på Aker Brygge?", a: "Gjennomsnittlig kvadratmeterpris er ca. 148 200 kr/m² — blant de aller høyeste i Norge." },
      { q: "Er Aker Brygge en god investering?", a: "Aker Brygge og Tjuvholmen har hatt stabil prisvekst siden 2010 og er ansett som svært trygge investeringer." },
      { q: "Hva er forskjellen på Aker Brygge og Tjuvholmen?", a: "Tjuvholmen er en kunstøy ved siden av Aker Brygge — mer eksklusiv og moderne, med Astrup Fearnley-museet. Prisene på Tjuvholmen er litt høyere." },
    ],
  },
  bjolsen: {
    slug: "bjolsen",
    name: "Bjølsen",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "12 000",
    avgSqmPrice: 93400,
    avgSqmPriceYoY: 6.3,
    priceSegment: "Høyt",
    transitScore: "Godt",
    topStreets: ["Bjølsenveien", "Dælenenggata", "Nordre gate"],
    metaTitle: "Bjølsen Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Bjølsen i Oslo. Gjennomsnittlig kvadratmeterpris: 93 400 kr/m².",
    heroHeading: "Bjølsen — Stille nabolag i rask forandring",
    heroSubheading: "Mellom Sagene og Torshov — prisvekstens nye vinner",
    introText: "Bjølsen er et rolig nabolag nord for Sagene som har sett sterk prisvekst de siste 5 årene. Nabolaget kjennetegnes av lavblokker og rekkehus fra 1950–1970-tallet, nå populært blant barnefamilier som presses ut av Grünerløkka.",
    transitText: "Trikkelinjene 11 og 12 stopper på Bjølsen. Storo T-bane er 10 minutters gange nordover.",
    faq: [
      { q: "Hva er prisen per m² i Bjølsen?", a: "Gjennomsnittlig kvadratmeterpris er ca. 93 400 kr/m²." },
      { q: "Er Bjølsen trygt?", a: "Bjølsen er et rolig og trygt nabolag, populært blant barnefamilier." },
      { q: "Hva er kollektivdekningen i Bjølsen?", a: "Trikkelinjene 11 og 12 betjener Bjølsen direkte. Storo T-bane er ca. 10 minutters gange." },
    ],
  },
  "kiellands-plass": {
    slug: "kiellands-plass",
    name: "Kiellands plass",
    city: "Oslo",
    citySlug: "oslo",
    kommunenummer: "0301",
    population: "9 000",
    avgSqmPrice: 95600,
    avgSqmPriceYoY: 5.8,
    priceSegment: "Høyt",
    transitScore: "Godt",
    topStreets: ["Seilduksgata", "Waldemar Thranes gate", "Bentsebrugata"],
    metaTitle: "Kiellands plass Oslo — Boligpriser og nabolagsdata 2026 | Verdikart",
    metaDescription: "Boligpriser og nabolagsdata for Kiellands plass i Oslo. Gjennomsnittlig kvadratmeterpris: 95 600 kr/m².",
    heroHeading: "Kiellands plass — Indre øst med sjel",
    heroSubheading: "Bydelsplassen, Akerselva og kafékulturen",
    introText: "Kiellands plass er et levende nabolag rundt den beplantede plassen av samme navn. Nabolaget er populært blant unge og har en aktiv kaféscene. Nærhet til Akerselva og god trikkedekning gjør det attraktivt.",
    transitText: "Trikkelinje 11, 12, 18 betjener Schous plass og Dælenenga, begge innen gangavstand.",
    faq: [
      { q: "Hva koster bolig på Kiellands plass?", a: "Gjennomsnittlig kvadratmeterpris er ca. 95 600 kr/m²." },
      { q: "Er Kiellands plass trygt?", a: "Kiellands plass er trygt og livlig med mye aktivitet." },
      { q: "Hva er nærmeste T-bane?", a: "Grønland T-bane er ca. 12 minutters gange. Trikken er primært transportmiddel her." },
    ],
  },
};

export function getArea(slug: string): AreaData | undefined {
  return areas[slug];
}

export function getAllAreaSlugs(): Array<{ area: string }> {
  return Object.keys(areas)
    .filter((key) => areas[key].slug === key) // deduplicate aliases
    .map((area) => ({ area }));
}
