export interface BydelData {
  slug: string;
  name: string;
  avgSqmPrice: number;
  avgSqmPriceYoY: number;
  population: string;
  kommunenummer: string;
  priceSegment: "Lavt" | "Middels" | "Høyt" | "Svært høyt";
  transitScore: "Utmerket" | "Godt" | "Middels" | "Begrenset";
  topStreets: string[];
  metaTitle: string;
  metaDescription: string;
  heroHeading: string;
  introText: string;
  transitText: string;
  faq: Array<{ q: string; a: string }>;
}

export const bydeler: Record<string, BydelData> = {
  frogner: { slug: "frogner", name: "Frogner", avgSqmPrice: 151900, avgSqmPriceYoY: 5.2, population: "60 000", kommunenummer: "0301", priceSegment: "Svært høyt", transitScore: "Utmerket", topStreets: ["Bygdøy allé", "Frognerveien", "Drammensveien"], metaTitle: "Frogner bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Frogner i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 151 900 kr/m².", heroHeading: "Frogner — Oslos dyreste bydel", introText: "Frogner bydel er Oslos mest eksklusive. Med Frognerparken, ambassadestrøk og art nouveau-bygg er dette den mest attraktive adressen for kapitalsterke kjøpere. Gjennomsnittsprisen er blant landets høyeste.", transitText: "T-bane linje 1, trikkelinjene 12 og 19 samt en rekke busslinjer gir utmerket dekning.", faq: [{ q: "Hva er gjennomsnittsprisen i Frogner bydel?", a: "151 900 kr/m² (SSB 2024)." }, { q: "Hva er de dyreste gatene i Frogner?", a: "Bygdøy allé, Drammensveien og Frognerveien topper prisoversikten." }, { q: "Er Frogner trygt?", a: "Ja, Frogner er blant Oslos tryggeste bydeler med svært lav kriminalitet." }] },
  grunerlokka: { slug: "grunerlokka", name: "Grünerløkka", avgSqmPrice: 112400, avgSqmPriceYoY: 6.1, population: "55 000", kommunenummer: "0301", priceSegment: "Høyt", transitScore: "Utmerket", topStreets: ["Thorvald Meyers gate", "Markveien", "Olaf Ryes plass"], metaTitle: "Grünerløkka bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Grünerløkka i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 112 400 kr/m².", heroHeading: "Grünerløkka — Kultur, kaffe og urban puls", introText: "Grünerløkka bydel er Oslos kulturelle hjerte. Akerselva, markeder, streetfood og mursteinsbygg fra 1880-tallet gjør dette til den mest etterspurte bydelen blant unge profesjonelle.", transitText: "Trikkelinjene 11, 12, 18 løper gjennom bydelen. T-bane via Grønland og Storo.", faq: [{ q: "Hva er gjennomsnittsprisen på Grünerløkka?", a: "112 400 kr/m² — opp 6,1 % siste år." }, { q: "Er Grünerløkka dyrt?", a: "Midt i Oslo-spekteret. Dyrere enn østkanten, vesentlig billigere enn Frogner." }, { q: "Hva er nærmeste T-bane til Grünerløkka?", a: "Grønland stasjon og Storo stasjon er de nærmeste T-banestasjonene." }] },
  "st-hanshaugen": { slug: "st-hanshaugen", name: "St. Hanshaugen", avgSqmPrice: 110200, avgSqmPriceYoY: 4.8, population: "38 000", kommunenummer: "0301", priceSegment: "Høyt", transitScore: "Utmerket", topStreets: ["Ullevålsveien", "St. Olavs gate", "Pilestredet"], metaTitle: "St. Hanshaugen bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for St. Hanshaugen i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 110 200 kr/m².", heroHeading: "St. Hanshaugen — Parken og det beste av indre vest", introText: "St. Hanshaugen bydel dekker området rundt den populære parken av samme navn. Bydelen er kjent for god service, høy trivsel og enkel tilgang til sentrum.", transitText: "Nationaltheatret og Stortinget T-banestasjoner er innen gangavstand. Trikkelinjene 17 og 18.", faq: [{ q: "Hva er prisen per m² i St. Hanshaugen?", a: "Ca. 110 200 kr/m²." }, { q: "Er det barnehager i St. Hanshaugen?", a: "Ja, bydelen har god dekning av kommunale og private barnehager." }, { q: "Hva er nærmeste T-bane?", a: "Nationaltheatret og Stortinget stasjoner." }] },
  sagene: { slug: "sagene", name: "Sagene", avgSqmPrice: 98700, avgSqmPriceYoY: 5.5, population: "45 000", kommunenummer: "0301", priceSegment: "Høyt", transitScore: "Godt", topStreets: ["Sandakerveien", "Vogts gate", "Torshov"], metaTitle: "Sagene bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Sagene i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 98 700 kr/m².", heroHeading: "Sagene — Torshov, Akerselva og prisoppgang", introText: "Sagene bydel har gjennomgått en markant gentrifisering. Torshov er nå et trendy nabolag med kafeer og Akerselva som grønn korridor.", transitText: "Trikkelinjene 11, 12 og T-bane via Storo dekker bydelen godt.", faq: [{ q: "Hva koster bolig i Sagene bydel?", a: "Ca. 98 700 kr/m²." }, { q: "Hva skjer i Sagene?", a: "Torshov har blitt Oslos nye trendy nabolag med kaféer, markeder og aktivt kulturliv." }, { q: "Er Sagene trygt?", a: "Sagene er trygt og har blitt tryggere i takt med gentrifiseringen." }] },
  "nordre-aker": { slug: "nordre-aker", name: "Nordre Aker", avgSqmPrice: 104500, avgSqmPriceYoY: 4.2, population: "52 000", kommunenummer: "0301", priceSegment: "Høyt", transitScore: "Godt", topStreets: ["Tåsen", "Kjelsåsveien", "Sandakerveien"], metaTitle: "Nordre Aker bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Nordre Aker i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 104 500 kr/m².", heroHeading: "Nordre Aker — Rolig og familievennlig nord i Oslo", introText: "Nordre Aker er en rolig bydel nord i Oslo, populær blant barnefamilier. Boligmassen domineres av eneboliger og rekkehus. Marka er innen sykkelavstand.", transitText: "T-bane linje 4 og 5 betjener Kjelsås og Tåsen. Busslinjer dekker hele bydelen.", faq: [{ q: "Hva er prisen per m² i Nordre Aker?", a: "Ca. 104 500 kr/m²." }, { q: "Er Nordre Aker familievennlig?", a: "Ja, en av Oslos mest familievennlige bydeler med gode skoler og nærhet til marka." }, { q: "Hva er nærmeste T-bane?", a: "Kjelsås og Tåsen på linje 4/5." }] },
  "vestre-aker": { slug: "vestre-aker", name: "Vestre Aker", avgSqmPrice: 118300, avgSqmPriceYoY: 3.9, population: "50 000", kommunenummer: "0301", priceSegment: "Svært høyt", transitScore: "Godt", topStreets: ["Holmenkollen", "Røa", "Gressbanen"], metaTitle: "Vestre Aker bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Vestre Aker i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 118 300 kr/m².", heroHeading: "Vestre Aker — Holmenkollen og eksklusivt villastrøk", introText: "Vestre Aker er kjent for Holmenkollen, store villaer og direkte tilgang til Nordmarka. Bydelen er populær blant familier og pensjonister som ønsker ro, natur og prestisje.", transitText: "T-bane linje 1 (Holmenkollen/Frognerseteren) gir direkte forbindelse til sentrum.", faq: [{ q: "Hva er prisen per m² i Vestre Aker?", a: "Ca. 118 300 kr/m² — blant Oslos høyeste." }, { q: "Hva er Vestre Aker kjent for?", a: "Holmenkollen, Nordmarka-tilgang og store villaer." }, { q: "Hva er nærmeste T-bane?", a: "T-bane linje 1 betjener Vestre Aker med flere stasjoner (Røa, Holmenkollen etc.)." }] },
  ullern: { slug: "ullern", name: "Ullern", avgSqmPrice: 107800, avgSqmPriceYoY: 4.1, population: "34 000", kommunenummer: "0301", priceSegment: "Høyt", transitScore: "Godt", topStreets: ["Hoffsveien", "Skøyenveien", "Lilleaker"], metaTitle: "Ullern bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Ullern i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 107 800 kr/m².", heroHeading: "Ullern — Skøyen, Lilleaker og sjøfronten", introText: "Ullern bydel inkluderer Skøyen og Lilleaker, to av Oslos mest attraktive næringslivs- og boligkorridorer. Sjøfronten langs Bestumkilen er et trekkplaster.", transitText: "T-bane via Skøyen (tog til Oslo S 8 min) og busslinjer langs Hoffsveien.", faq: [{ q: "Hva er prisen per m² i Ullern?", a: "Ca. 107 800 kr/m²." }, { q: "Er Ullern bra for pendlere?", a: "Ja, Skøyen stasjon er et av Oslos viktigste knutepunkter med tog, T-bane og buss." }, { q: "Hva er Ullern kjent for?", a: "Skøyen næringspark, sjøfronten og gode skoler." }] },
  grorud: { slug: "grorud", name: "Grorud", avgSqmPrice: 58200, avgSqmPriceYoY: 3.2, population: "27 000", kommunenummer: "0301", priceSegment: "Lavt", transitScore: "Middels", topStreets: ["Ammerudveien", "Grorudveien", "Rødtvetveien"], metaTitle: "Grorud bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Grorud i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 58 200 kr/m². Rimelige boliger i Oslo.", heroHeading: "Grorud — Rimelig og grønt i Groruddalen", introText: "Grorud bydel tilbyr de rimeligste boligprisene i Oslo for de som aksepterer lengre pendleavstand. Store grønne arealer og et aktivt lokalmiljø.", transitText: "T-bane linje 4 (Vestli/Bergkrystallen) betjener Grorud. Buss til Storo og sentrum.", faq: [{ q: "Hva er prisen per m² i Grorud?", a: "Ca. 58 200 kr/m² — blant Oslos billigste." }, { q: "Er Grorud trygt?", a: "Grorud har hatt utfordringer men er under positiv utvikling. Tryggere i dag enn for 10 år siden." }, { q: "Hva er reisetiden til sentrum?", a: "Ca. 25–35 minutter med T-bane til Oslo S." }] },
  stovner: { slug: "stovner", name: "Stovner", avgSqmPrice: 55400, avgSqmPriceYoY: 2.8, population: "33 000", kommunenummer: "0301", priceSegment: "Lavt", transitScore: "Middels", topStreets: ["Stovner senter", "Fossum", "Vestlisvingen"], metaTitle: "Stovner bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Stovner i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 55 400 kr/m².", heroHeading: "Stovner — Oslos rimeligste bydel", introText: "Stovner er Oslos rimeligste bydel med et tilbud for førstegangskjøpere. Stovner senter er bydelens handelshub og T-bane gir greit kollektivtilbud.", transitText: "T-bane linje 5 (Vestli) betjener Stovner. Stovner stasjon er et lokalt knutepunkt.", faq: [{ q: "Hva er prisen per m² i Stovner?", a: "Ca. 55 400 kr/m² — Oslos laveste." }, { q: "Er Stovner bra for førstegangskjøpere?", a: "Ja, Stovner er et av få steder i Oslo der førstegangskjøpere kan kjøpe uten hjelp fra foreldre." }, { q: "Hva er reisetiden til sentrum?", a: "Ca. 30–40 minutter med T-bane." }] },
  "sondre-nordstrand": { slug: "sondre-nordstrand", name: "Søndre Nordstrand", avgSqmPrice: 54100, avgSqmPriceYoY: 2.5, population: "39 000", kommunenummer: "0301", priceSegment: "Lavt", transitScore: "Middels", topStreets: ["Mortensrud", "Holmlia", "Prinsdal"], metaTitle: "Søndre Nordstrand bydel Oslo — Boligpriser 2026 | Verdikart", metaDescription: "Boligpriser og bydelsdata for Søndre Nordstrand i Oslo 2026. Gjennomsnittlig kvadratmeterpris: 54 100 kr/m².", heroHeading: "Søndre Nordstrand — Rimelig sydover med fjordnærhet", introText: "Søndre Nordstrand er Oslos sørligste bydel og tilbyr rimelige boliger med nærhet til Oslofjorden og Nordstrand badeplass. Populær blant familier som vil ha plass til pengene.", transitText: "T-bane linje 3 (Mortensrud) og buss T-bane til Ljabru og Holmlia.", faq: [{ q: "Hva er prisen per m² i Søndre Nordstrand?", a: "Ca. 54 100 kr/m² — Oslos nest laveste." }, { q: "Er Søndre Nordstrand familievennlig?", a: "Ja, god plass, grønne arealer og lavere priser gjør det populært blant barnefamilier." }, { q: "Hva er nærmeste T-bane?", a: "Mortensrud (linje 3) og Holmlia stasjon betjener bydelen." }] },
};

export function getBydel(slug: string): BydelData | undefined {
  return bydeler[slug];
}

export function getAllBydelSlugs(): { bydel: string }[] {
  return Object.keys(bydeler).map((s) => ({ bydel: s }));
}
