import { describe, it, expect } from "vitest";
import {
  KOMMUNE_CANDIDATES,
  COMPARISON_ADDRESSES,
} from "@/data/pendlings-poeng-candidates";
import { PENDLINGS_POENG_LANDING_DATA } from "@/data/pendlings-poeng-landing-data";
import { selectWorkCenterByKommune } from "@/lib/scoring/work-centers";
import { kommunePopulation } from "@/data/kommune-population";

/**
 * Landing-data contract tests. The cached snapshot in
 * pendlings-poeng-landing-data.ts is regenerated by the refresh script; these
 * tests enforce that each snapshot has the shape the page expects, that every
 * candidate kommune still resolves to a valid center (catches stale
 * knr → fylke mappings after kommune mergers), and that the ranking respects
 * the population-weighted tiebreaker.
 */
const WORK_CENTER_KNR = new Set([
  "0301",
  "4601",
  "5001",
  "1103",
  "5501",
  "4204",
]);

describe("pendlings-poeng candidate data", () => {
  it("every kommune candidate has a resolvable work center", () => {
    for (const c of KOMMUNE_CANDIDATES) {
      const center = selectWorkCenterByKommune(c.kommunenummer);
      expect(center, `knr ${c.kommunenummer} (${c.kommunenavn})`).not.toBeNull();
      expect(center!.id).toBe(c.expectedCenter);
    }
  });

  it("kommune candidates have unique slugs and knr", () => {
    const slugs = new Set(KOMMUNE_CANDIDATES.map((c) => c.slug));
    const knrs = new Set(KOMMUNE_CANDIDATES.map((c) => c.kommunenummer));
    expect(slugs.size).toBe(KOMMUNE_CANDIDATES.length);
    expect(knrs.size).toBe(KOMMUNE_CANDIDATES.length);
  });

  it("includes all six work-center kommuner", () => {
    const candidateKnr = new Set(KOMMUNE_CANDIDATES.map((c) => c.kommunenummer));
    for (const knr of Array.from(WORK_CENTER_KNR)) {
      expect(candidateKnr.has(knr), `missing work-center knr ${knr}`).toBe(true);
    }
  });

  it("comparison addresses have valid coordinates", () => {
    for (const a of COMPARISON_ADDRESSES) {
      expect(a.lat).toBeGreaterThan(55);
      expect(a.lat).toBeLessThan(72);
      expect(a.lon).toBeGreaterThan(4);
      expect(a.lon).toBeLessThan(32);
    }
  });
});

describe("pendlings-poeng landing data snapshot", () => {
  it("has a generatedAt timestamp and both kommune lists populated", () => {
    const {
      generatedAt,
      workCenterKommuner,
      topPendlerKommuner,
      comparisons,
    } = PENDLINGS_POENG_LANDING_DATA;
    expect(generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(workCenterKommuner.length).toBe(6);
    expect(topPendlerKommuner.length).toBe(10);
    expect(comparisons.length).toBeGreaterThanOrEqual(4);
  });

  it("work-center list contains exactly the six work-center kommuner", () => {
    const knr = new Set(
      PENDLINGS_POENG_LANDING_DATA.workCenterKommuner.map((r) => r.kommunenummer),
    );
    expect(knr).toEqual(WORK_CENTER_KNR);
  });

  it("top pendler-kommuner excludes every work-center kommune", () => {
    for (const row of PENDLINGS_POENG_LANDING_DATA.topPendlerKommuner) {
      expect(WORK_CENTER_KNR.has(row.kommunenummer), row.kommunenavn).toBe(false);
    }
  });

  it("both lists sort by total desc then population desc then D2D asc", () => {
    const check = (rows: ReadonlyArray<{ total: number; population: number; doorToDoorMinutes: number }>) => {
      for (let i = 1; i < rows.length; i++) {
        const prev = rows[i - 1];
        const cur = rows[i];
        if (prev.total !== cur.total) {
          expect(prev.total).toBeGreaterThan(cur.total);
        } else if (prev.population !== cur.population) {
          expect(prev.population).toBeGreaterThan(cur.population);
        } else {
          expect(prev.doorToDoorMinutes).toBeLessThanOrEqual(cur.doorToDoorMinutes);
        }
      }
    };
    check(PENDLINGS_POENG_LANDING_DATA.workCenterKommuner);
    check(PENDLINGS_POENG_LANDING_DATA.topPendlerKommuner);
  });

  it("row.population matches kommune-population.ts", () => {
    const all = [
      ...PENDLINGS_POENG_LANDING_DATA.workCenterKommuner,
      ...PENDLINGS_POENG_LANDING_DATA.topPendlerKommuner,
    ];
    for (const row of all) {
      const fromTable = kommunePopulation[row.kommunenummer]?.population ?? 0;
      expect(row.population).toBe(fromTable);
    }
  });

  it("ranks within each list are 1..n", () => {
    PENDLINGS_POENG_LANDING_DATA.workCenterKommuner.forEach((row, i) => {
      expect(row.rank).toBe(i + 1);
      expect(row.total).toBeGreaterThanOrEqual(0);
      expect(row.total).toBeLessThanOrEqual(100);
    });
    PENDLINGS_POENG_LANDING_DATA.topPendlerKommuner.forEach((row, i) => {
      expect(row.rank).toBe(i + 1);
    });
  });
});
