// NOTE: This file must ONLY be imported via dynamic(() => import(...), { ssr: false })
// Never import it directly — Leaflet requires window/document at module evaluation time.
// Leaflet's stylesheet is code-split with this chunk so it never hits the homepage.
"use client";

import "leaflet/dist/leaflet.css";
import { useEffect, useRef, useState } from "react";
import { useRouter, useSearchParams, usePathname } from "next/navigation";
import Link from "next/link";
import dynamic from "next/dynamic";
import { ChevronRight, TrendingUp, Info } from "lucide-react";
import { formatPct } from "@/lib/format";
import { MapContainer, TileLayer, CircleMarker, Tooltip, useMap } from "react-leaflet";
import type { WorkCenterId } from "@/lib/scoring/work-centers";
import { HEATMAP_BUCKETS } from "@/lib/heatmapColor";

const BykartHeatmapLayer = dynamic(
  () => import("@/components/BykartHeatmapLayer"),
  { ssr: false, loading: () => null },
);

interface City {
  slug: string;
  name: string;
  avgSqmPrice: number;
  yoy: number;
  lat: number;
  lon: number;
}

// Real lat/lon for 15 Norwegian cities
const CITIES: City[] = [
  { slug: "oslo",         name: "Oslo",         avgSqmPrice: 94200, yoy: 5.1, lat: 59.9139, lon: 10.7522 },
  { slug: "baerum",       name: "Bærum",        avgSqmPrice: 72500, yoy: 4.8, lat: 59.8939, lon: 10.5456 },
  { slug: "fredrikstad",  name: "Fredrikstad",  avgSqmPrice: 36900, yoy: 6.1, lat: 59.2181, lon: 10.9298 },
  { slug: "sarpsborg",    name: "Sarpsborg",    avgSqmPrice: 32400, yoy: 5.7, lat: 59.2839, lon: 11.1094 },
  { slug: "drammen",      name: "Drammen",      avgSqmPrice: 44700, yoy: 5.3, lat: 59.7440, lon: 10.2046 },
  { slug: "skien",        name: "Skien",        avgSqmPrice: 28900, yoy: 4.9, lat: 59.2096, lon: 9.6089 },
  { slug: "kristiansand", name: "Kristiansand", avgSqmPrice: 42600, yoy: 5.9, lat: 58.1599, lon: 8.0182 },
  { slug: "stavanger",    name: "Stavanger",    avgSqmPrice: 57800, yoy: 7.4, lat: 58.9700, lon: 5.7331 },
  { slug: "sandnes",      name: "Sandnes",      avgSqmPrice: 49200, yoy: 6.8, lat: 58.8516, lon: 5.7347 },
  { slug: "bergen",       name: "Bergen",       avgSqmPrice: 62400, yoy: 4.3, lat: 60.3913, lon: 5.3221 },
  { slug: "trondheim",    name: "Trondheim",    avgSqmPrice: 54100, yoy: 6.2, lat: 63.4305, lon: 10.3951 },
  { slug: "tromso",       name: "Tromsø",       avgSqmPrice: 52300, yoy: 4.1, lat: 69.6492, lon: 18.9553 },
  { slug: "bodo",         name: "Bodø",         avgSqmPrice: 41200, yoy: 6.5, lat: 67.2804, lon: 14.4049 },
  { slug: "arendal",      name: "Arendal",      avgSqmPrice: 36100, yoy: 5.2, lat: 58.4612, lon: 8.7723 },
  { slug: "hamar",        name: "Hamar",        avgSqmPrice: 38200, yoy: 4.6, lat: 60.7945, lon: 11.0679 },
];

const MAX_PRICE = Math.max(...CITIES.map((c) => c.avgSqmPrice));
const MIN_PRICE = Math.min(...CITIES.map((c) => c.avgSqmPrice));

function priceColor(price: number): string {
  const t = (price - MIN_PRICE) / (MAX_PRICE - MIN_PRICE);
  if (t < 0.5) {
    const r = Math.round(34 + t * 2 * (251 - 34));
    const g = Math.round(197 + t * 2 * (191 - 197));
    const b = Math.round(94 + t * 2 * (36 - 94));
    return `rgb(${r},${g},${b})`;
  }
  const t2 = (t - 0.5) * 2;
  const r = Math.round(251 + t2 * (239 - 251));
  const g = Math.round(191 + t2 * (68 - 191));
  const b = Math.round(36 + t2 * (68 - 36));
  return `rgb(${r},${g},${b})`;
}

function bubbleRadius(price: number): number {
  const t = (price - MIN_PRICE) / (MAX_PRICE - MIN_PRICE);
  return 8 + t * 16; // 8–24px radius
}

// Fix narrow-width bug: fires invalidateSize after mount
function MapReady() {
  const map = useMap();
  useEffect(() => {
    const t1 = setTimeout(() => map.invalidateSize({ animate: false }), 80);
    const t2 = setTimeout(() => map.invalidateSize({ animate: false }), 400);
    return () => {
      clearTimeout(t1);
      clearTimeout(t2);
    };
  }, [map]);
  return null;
}

/* ── Heatmap view config ─────────────────────────────────────────────────
 * Each entry needs: a pre-computed data file at
 * src/data/bykart-heatmap-<id>.ts (generated by
 * scripts/refresh-bykart-heatmap.ts), and a { center, zoom } tuned to show
 * the full radiusKm scoring disk at the configured zoom level.
 */
interface HeatmapView {
  id: WorkCenterId;
  label: string;
  center: [number, number];
  zoom: number;
  radiusKm: number;
}

const AVAILABLE_HEATMAPS: ReadonlyArray<HeatmapView> = [
  { id: "oslo",         label: "Oslo",         center: [59.9109, 10.7527], zoom: 11, radiusKm: 25 },
  { id: "bergen",       label: "Bergen",       center: [60.3928,  5.3240], zoom: 11, radiusKm: 20 },
  { id: "stavanger",    label: "Stavanger",    center: [58.9694,  5.7332], zoom: 11, radiusKm: 20 },
  { id: "trondheim",    label: "Trondheim",    center: [63.4362, 10.3984], zoom: 12, radiusKm: 15 },
  { id: "kristiansand", label: "Kristiansand", center: [58.1467,  7.9956], zoom: 12, radiusKm: 15 },
  { id: "tromso",       label: "Tromsø",       center: [69.6489, 18.9551], zoom: 12, radiusKm: 15 },
];

const NATIONAL_VIEW = { center: [64.5, 17] as [number, number], zoom: 4 };

// Fly the map to the target view when the selection changes. No-op on first
// render (the MapContainer is already centred on the initial view).
function MapViewController({ view }: { view: "oversikt" | WorkCenterId }) {
  const map = useMap();
  const firstMount = useRef(true);
  useEffect(() => {
    if (firstMount.current) {
      firstMount.current = false;
      return;
    }
    if (view === "oversikt") {
      map.flyTo(NATIONAL_VIEW.center, NATIONAL_VIEW.zoom, { duration: 0.9 });
    } else {
      const target = AVAILABLE_HEATMAPS.find((h) => h.id === view);
      if (target) map.flyTo(target.center, target.zoom, { duration: 0.9 });
    }
  }, [map, view]);
  return null;
}

function isWorkCenterView(
  v: string | null,
): v is WorkCenterId {
  return AVAILABLE_HEATMAPS.some((h) => h.id === v);
}

export default function CityOverviewMapInner() {
  const [selected, setSelected] = useState<City | null>(null);

  const router = useRouter();
  const pathname = usePathname();
  const searchParams = useSearchParams();

  // view is the source of truth; URL mirrors it via ?view=.
  const initialView = (() => {
    const raw = searchParams.get("view");
    return isWorkCenterView(raw) ? raw : ("oversikt" as const);
  })();
  const [view, setView] = useState<"oversikt" | WorkCenterId>(initialView);

  // Push view changes into the URL as ?view=<city>; "oversikt" clears the param.
  useEffect(() => {
    const params = new URLSearchParams(searchParams.toString());
    if (view === "oversikt") params.delete("view");
    else params.set("view", view);
    const next = params.toString();
    const url = next ? `${pathname}?${next}` : pathname;
    router.replace(url, { scroll: false });
    // searchParams/pathname/router identity changes shouldn't retrigger this.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [view]);

  // Sync from URL → state for back/forward navigation.
  useEffect(() => {
    const raw = searchParams.get("view");
    const next: "oversikt" | WorkCenterId = isWorkCenterView(raw) ? raw : "oversikt";
    setView((prev) => (prev === next ? prev : next));
  }, [searchParams]);

  // Plausible: fire once per city transition. No event for "oversikt" — the
  // homepage map already has national-view analytics.
  const lastTracked = useRef<string | null>(null);
  useEffect(() => {
    if (view === "oversikt" || lastTracked.current === view) return;
    lastTracked.current = view;
    const plausible = (window as unknown as {
      plausible?: (
        event: string,
        options?: { props?: Record<string, string | number | boolean> },
      ) => void;
    }).plausible;
    if (typeof plausible !== "function") return;
    try {
      plausible("bykart_heatmap_viewed", { props: { city: view } });
    } catch {
      // Analytics must never break the render.
    }
  }, [view]);

  const initialMapCenter: [number, number] =
    initialView === "oversikt"
      ? NATIONAL_VIEW.center
      : AVAILABLE_HEATMAPS.find((h) => h.id === initialView)?.center ?? NATIONAL_VIEW.center;
  const initialMapZoom =
    initialView === "oversikt"
      ? NATIONAL_VIEW.zoom
      : AVAILABLE_HEATMAPS.find((h) => h.id === initialView)?.zoom ?? NATIONAL_VIEW.zoom;

  const isHeatmap = view !== "oversikt";
  const currentView =
    view !== "oversikt"
      ? AVAILABLE_HEATMAPS.find((h) => h.id === view)
      : undefined;

  return (
    <div className="space-y-4">
      {/* View selector */}
      <div className="flex flex-wrap items-center gap-2">
        <button
          onClick={() => setView("oversikt")}
          className={`rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
            view === "oversikt"
              ? "border-accent bg-accent text-accent-ink"
              : "border-card-border bg-card-bg text-text-secondary hover:border-accent/40 hover:text-foreground"
          }`}
        >
          Oversikt
        </button>
        {AVAILABLE_HEATMAPS.map((h) => (
          <button
            key={h.id}
            onClick={() => setView(h.id)}
            className={`rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
              view === h.id
                ? "border-accent bg-accent text-accent-ink"
                : "border-card-border bg-card-bg text-text-secondary hover:border-accent/40 hover:text-foreground"
            }`}
          >
            {h.label}
          </button>
        ))}
      </div>

      <div className="grid gap-6 lg:grid-cols-[1fr_300px]">
      {/* Map */}
      <div
        className="relative rounded-xl border border-card-border bg-card-bg overflow-hidden"
        style={{ minHeight: 480 }}
      >
        <MapContainer
          center={initialMapCenter}
          zoom={initialMapZoom}
          className="h-[480px] w-full"
          zoomControl={true}
          scrollWheelZoom={false}
          attributionControl={true}
          preferCanvas={true}
        >
          <MapReady />
          <MapViewController view={view} />
          <TileLayer
            attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="https://carto.com/attributions">CARTO</a>'
            url="https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"
            subdomains="abcd"
            maxZoom={20}
          />

          {!isHeatmap &&
            CITIES.map((city) => {
            const r = bubbleRadius(city.avgSqmPrice);
            const color = priceColor(city.avgSqmPrice);
            const isSelected = selected?.slug === city.slug;
            return (
              <CircleMarker
                key={city.slug}
                center={[city.lat, city.lon]}
                radius={r}
                pathOptions={{
                  color: isSelected ? "#ffffff" : "rgba(255,255,255,0.35)",
                  weight: isSelected ? 2 : 1,
                  fillColor: color,
                  fillOpacity: isSelected ? 1 : 0.8,
                }}
                eventHandlers={{
                  click: () => setSelected(isSelected ? null : city),
                }}
              >
                <Tooltip direction="top" offset={[0, -4]} opacity={1} permanent={false}>
                  <span style={{ color: "#111", fontWeight: 600 }}>
                    {city.name}
                  </span>
                  <br />
                  <span style={{ color: "#444", fontSize: "11px" }}>
                    {city.avgSqmPrice.toLocaleString("nb-NO")} kr/m²
                  </span>
                </Tooltip>
              </CircleMarker>
            );
          })}

          {isHeatmap && <BykartHeatmapLayer city={view as WorkCenterId} />}
        </MapContainer>

        {/* Legend */}
        {!isHeatmap ? (
          <div className="absolute bottom-3 left-3 z-[400] rounded-lg border border-card-border bg-background/90 p-3 backdrop-blur-sm text-xs">
            <p className="mb-1.5 font-semibold text-text-secondary">Kvadratmeterpris</p>
            <div className="flex items-center gap-2">
              <div
                className="h-3 w-16 rounded-full"
                style={{
                  background: "linear-gradient(to right, #22c55e, #fbbf24, #ef4444)",
                }}
              />
              <span className="text-text-tertiary">
                {MIN_PRICE.toLocaleString("nb-NO")}
              </span>
              <span className="text-text-tertiary ml-auto">
                {MAX_PRICE.toLocaleString("nb-NO")}
              </span>
            </div>
            <p className="mt-1 text-[10px] text-text-tertiary">
              kr/m² · klikk for detaljer
            </p>
          </div>
        ) : (
          <div className="absolute bottom-3 left-3 z-[400] rounded-lg border border-card-border bg-background/90 p-3 backdrop-blur-sm text-xs">
            <div className="mb-1.5 flex items-center gap-1.5">
              <p className="font-semibold text-text-secondary">Pendlings-poeng</p>
              <Link
                href="/pendlings-poeng"
                className="text-text-tertiary hover:text-accent"
                title="Les metodikken"
              >
                <Info className="h-3 w-3" strokeWidth={2} />
              </Link>
            </div>
            <div className="space-y-0.5">
              {HEATMAP_BUCKETS.map((b) => (
                <div key={b.label} className="flex items-center gap-2">
                  <div
                    className="h-2.5 w-4 rounded-sm"
                    style={{ background: b.color, opacity: 0.85 }}
                  />
                  <span className="text-text-tertiary tabular-nums">{b.label}</span>
                </div>
              ))}
            </div>
            {currentView && (
              <p className="mt-2 max-w-[200px] text-[10px] leading-snug text-text-tertiary">
                Radiusen dekker {currentView.radiusKm} km rundt sentrum og
                inkluderer både urbane og spredtbygde områder. Røde områder
                betyr at pendling til sentrum tar tid, ikke at stedet er
                dårlig.
              </p>
            )}
            <p className="mt-1.5 text-[10px] text-text-tertiary">
              hover for verdi · klikk på en hex for detaljer
            </p>
          </div>
        )}
      </div>

      {/* Side panel */}
      <div className="space-y-3">
        {selected ? (
          <div className="rounded-xl border border-accent/30 bg-card-bg p-5">
            <div className="mb-3 flex items-start justify-between">
              <h2 className="text-lg font-bold">{selected.name}</h2>
              <button
                onClick={() => setSelected(null)}
                className="text-text-tertiary hover:text-foreground text-xs"
              >
                ✕
              </button>
            </div>
            <div className="space-y-3 mb-4">
              <div className="rounded-lg bg-background p-3">
                <p className="text-xs text-text-tertiary">Kvadratmeterpris</p>
                <p className="text-2xl font-bold tabular-nums">
                  {selected.avgSqmPrice.toLocaleString("nb-NO")} kr/m²
                </p>
              </div>
              <div className="rounded-lg bg-background p-3">
                <p className="text-xs text-text-tertiary">Prisvekst (12 mnd)</p>
                <p className="text-xl font-bold text-green-400 flex items-center gap-1">
                  <TrendingUp className="h-4 w-4" strokeWidth={2} />
                  +{formatPct(selected.yoy)}
                </p>
              </div>
            </div>
            <Link
              href={`/by/${selected.slug}`}
              className="flex w-full items-center justify-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-accent-ink transition-opacity hover:opacity-80"
            >
              Se full byrapport
              <ChevronRight className="h-4 w-4" strokeWidth={2} />
            </Link>
          </div>
        ) : (
          <div className="rounded-xl border border-card-border bg-card-bg p-5">
            <p className="mb-3 text-sm font-semibold">Alle byer</p>
            <div className="space-y-1.5 max-h-[380px] overflow-y-auto pr-1">
              {[...CITIES]
                .sort((a, b) => b.avgSqmPrice - a.avgSqmPrice)
                .map((city) => (
                  <button
                    key={city.slug}
                    onClick={() => setSelected(city)}
                    className="flex w-full items-center justify-between rounded-lg px-3 py-2 text-left text-sm transition-colors hover:bg-background"
                  >
                    <div className="flex items-center gap-2">
                      <div
                        className="h-2.5 w-2.5 rounded-full shrink-0"
                        style={{ background: priceColor(city.avgSqmPrice) }}
                      />
                      <span className="font-medium">{city.name}</span>
                    </div>
                    <div className="text-right">
                      <p className="text-xs font-bold tabular-nums">
                        {city.avgSqmPrice.toLocaleString("nb-NO")}
                      </p>
                      <p className="text-[10px] text-green-400">+{formatPct(city.yoy)}</p>
                    </div>
                  </button>
                ))}
            </div>
          </div>
        )}

        {/* All-cities compare link */}
        <Link
          href="/sammenlign"
          className="flex items-center justify-center gap-2 rounded-xl border border-card-border bg-card-bg px-4 py-2.5 text-sm text-text-secondary transition-colors hover:border-accent/40 hover:text-foreground"
        >
          Sammenlign to adresser →
        </Link>
      </div>
      </div>
    </div>
  );
}
