/**
 * Pre-computed landing-page data for /klima-poeng.
 *
 * Regenerated by `scripts/refresh-klima-poeng-landing.ts`, which hits
 * NVE + Kartverket WMS for each kommune candidate (sentrum coord) and city
 * comparison point, then writes back the top-10 (safest) and bottom-10
 * (most exposed) kommune rankings + side-by-side comparison breakdowns.
 *
 * Ranking within each list:
 *   - Top:    total desc → population desc → kommunenavn asc
 *   - Bottom: total asc  → population desc → kommunenavn asc
 *
 * The page reads this file at build time. Refresh monthly, or after a
 * material change to NVE/Kartverket WMS layers (rare; aktsomhetskart are
 * republished yearly at most).
 *
 * DO NOT edit manually — re-run the refresh script instead.
 */

export interface KlimaComponentBar {
  value: string;
  score: number;
}

export interface KlimaRadonBar {
  value: string;
  score: number | null;
  assessed: boolean;
}

export interface KlimaComponentBars {
  flood: KlimaComponentBar;
  quickClay: KlimaComponentBar;
  skred: KlimaComponentBar;
  stormSurge: KlimaComponentBar;
  radon: KlimaRadonBar;
  klimaprofil: KlimaComponentBar;
}

export interface KlimaKommuneScoreRow {
  rank: number;
  kommunenummer: string;
  kommunenavn: string;
  slug: string;
  total: number;
  band: string;
  centerNote: string;
  population: number;
  fylkesnavn: string | null;
  components: KlimaComponentBars;
}

export interface KlimaComparisonSide {
  label: string;
  kommunenavn: string;
  total: number;
  band: string;
  fylkesnavn: string | null;
  components: KlimaComponentBars;
}

export interface KlimaComparisonRow {
  pairId: string;
  title: string;
  rationale: string;
  left: KlimaComparisonSide;
  right: KlimaComparisonSide;
}

export interface KlimaPoengLandingData {
  generatedAt: string;
  /** Number of kommuner successfully scored, of total candidates. */
  candidatesScored: number;
  candidatesTotal: number;
  /** Top 10 kommuner by mean Klima-poeng — the safest. */
  topSafe: ReadonlyArray<KlimaKommuneScoreRow>;
  /** Bottom 10 kommuner — the most climate-exposed of the candidate list. */
  bottomExposed: ReadonlyArray<KlimaKommuneScoreRow>;
  comparisons: ReadonlyArray<KlimaComparisonRow>;
}

export const KLIMA_POENG_LANDING_DATA: KlimaPoengLandingData = {
  generatedAt: "2026-04-23T18:45:12.472Z",
  candidatesScored: 357,
  candidatesTotal: 357,
  topSafe: [
  {
    "rank": 1,
    "kommunenummer": "4204",
    "kommunenavn": "Kristiansand",
    "slug": "kristiansand",
    "total": 95,
    "band": "Utmerket",
    "centerNote": "Kvadraturen",
    "population": 119287,
    "fylkesnavn": "Agder",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Lav",
        "score": 100,
        "assessed": true
      },
      "klimaprofil": {
        "value": "Agder",
        "score": 67
      }
    }
  },
  {
    "rank": 2,
    "kommunenummer": "4203",
    "kommunenavn": "Arendal",
    "slug": "arendal",
    "total": 95,
    "band": "Utmerket",
    "centerNote": "Arendal sentrum",
    "population": 46603,
    "fylkesnavn": "Agder",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Lav",
        "score": 100,
        "assessed": true
      },
      "klimaprofil": {
        "value": "Agder",
        "score": 67
      }
    }
  },
  {
    "rank": 3,
    "kommunenummer": "1103",
    "kommunenavn": "Stavanger",
    "slug": "stavanger",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Stavanger sentrum",
    "population": 151669,
    "fylkesnavn": "Rogaland",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Lav",
        "score": 100,
        "assessed": true
      },
      "klimaprofil": {
        "value": "Rogaland",
        "score": 58
      }
    }
  },
  {
    "rank": 4,
    "kommunenummer": "3207",
    "kommunenavn": "Nordre Follo",
    "slug": "nordre-follo",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Ski sentrum",
    "population": 65381,
    "fylkesnavn": "Oslo og Akershus",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Oslo og Akershus",
        "score": 64
      }
    }
  },
  {
    "rank": 5,
    "kommunenummer": "3103",
    "kommunenavn": "Moss",
    "slug": "moss",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Moss sentrum",
    "population": 53207,
    "fylkesnavn": "Østfold",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Østfold",
        "score": 67
      }
    }
  },
  {
    "rank": 6,
    "kommunenummer": "3222",
    "kommunenavn": "Lørenskog",
    "slug": "lorenskog",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Lørenskog sentrum",
    "population": 51511,
    "fylkesnavn": "Oslo og Akershus",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Oslo og Akershus",
        "score": 64
      }
    }
  },
  {
    "rank": 7,
    "kommunenummer": "3118",
    "kommunenavn": "Indre Østfold",
    "slug": "indre-ostfold",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Askim sentrum",
    "population": 47943,
    "fylkesnavn": "Østfold",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Østfold",
        "score": 67
      }
    }
  },
  {
    "rank": 8,
    "kommunenummer": "3101",
    "kommunenavn": "Halden",
    "slug": "halden",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Halden sentrum",
    "population": 32082,
    "fylkesnavn": "Østfold",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Østfold",
        "score": 67
      }
    }
  },
  {
    "rank": 9,
    "kommunenummer": "3303",
    "kommunenavn": "Kongsberg",
    "slug": "kongsberg",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Kongsberg sentrum",
    "population": 29169,
    "fylkesnavn": "Buskerud",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Buskerud",
        "score": 64
      }
    }
  },
  {
    "rank": 10,
    "kommunenummer": "3232",
    "kommunenavn": "Nittedal",
    "slug": "nittedal",
    "total": 94,
    "band": "Utmerket",
    "centerNote": "Rotnes",
    "population": 26032,
    "fylkesnavn": "Oslo og Akershus",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Oslo og Akershus",
        "score": 64
      }
    }
  }
],
  bottomExposed: [
  {
    "rank": 1,
    "kommunenummer": "4651",
    "kommunenavn": "Stryn",
    "slug": "stryn",
    "total": 40,
    "band": "Svak",
    "centerNote": "Kommunesentrum",
    "population": 0,
    "fylkesnavn": "Sogn og Fjordane",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Faresone",
        "score": 0
      },
      "skred": {
        "value": "Innenfor 3 aktsomhetsområder",
        "score": 20
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Sogn og Fjordane",
        "score": 60
      }
    }
  },
  {
    "rank": 2,
    "kommunenummer": "1506",
    "kommunenavn": "Molde",
    "slug": "molde",
    "total": 49,
    "band": "Svak",
    "centerNote": "Molde sentrum",
    "population": 33291,
    "fylkesnavn": "Møre og Romsdal",
    "components": {
      "flood": {
        "value": "Høy",
        "score": 0
      },
      "quickClay": {
        "value": "Faresone",
        "score": 0
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Møre og Romsdal",
        "score": 60
      }
    }
  },
  {
    "rank": 3,
    "kommunenummer": "3107",
    "kommunenavn": "Fredrikstad",
    "slug": "fredrikstad",
    "total": 51,
    "band": "Svak",
    "centerNote": "Fredrikstad stasjon",
    "population": 86243,
    "fylkesnavn": "Østfold",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Faresone",
        "score": 0
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Ekstremtilfelle",
        "score": 70
      },
      "radon": {
        "value": "Høy",
        "score": 20,
        "assessed": true
      },
      "klimaprofil": {
        "value": "Østfold",
        "score": 67
      }
    }
  },
  {
    "rank": 4,
    "kommunenummer": "4641",
    "kommunenavn": "Aurland",
    "slug": "aurland",
    "total": 52,
    "band": "Svak",
    "centerNote": "Aurlandsvangen",
    "population": 0,
    "fylkesnavn": "Sogn og Fjordane",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Innenfor snøskred",
        "score": 50
      },
      "stormSurge": {
        "value": "Flomutsatt i dag",
        "score": 0
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Sogn og Fjordane",
        "score": 60
      }
    }
  },
  {
    "rank": 5,
    "kommunenummer": "3312",
    "kommunenavn": "Lier",
    "slug": "lier",
    "total": 59,
    "band": "OK",
    "centerNote": "Lierbyen",
    "population": 28797,
    "fylkesnavn": "Buskerud",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Faresone",
        "score": 0
      },
      "skred": {
        "value": "Utenfor",
        "score": 100
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Buskerud",
        "score": 64
      }
    }
  },
  {
    "rank": 6,
    "kommunenummer": "4617",
    "kommunenavn": "Kvinnherad",
    "slug": "kvinnherad",
    "total": 59,
    "band": "OK",
    "centerNote": "Husnes",
    "population": 13236,
    "fylkesnavn": "Hordaland",
    "components": {
      "flood": {
        "value": "Lav",
        "score": 100
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Innenfor 2 aktsomhetsområder",
        "score": 20
      },
      "stormSurge": {
        "value": "Flomutsatt i dag",
        "score": 0
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Hordaland",
        "score": 60
      }
    }
  },
  {
    "rank": 7,
    "kommunenummer": "1824",
    "kommunenavn": "Vefsn",
    "slug": "vefsn",
    "total": 61,
    "band": "OK",
    "centerNote": "Mosjøen",
    "population": 13481,
    "fylkesnavn": "Nordland",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Innenfor 2 aktsomhetsområder",
        "score": 20
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Nordland",
        "score": 51
      }
    }
  },
  {
    "rank": 8,
    "kommunenummer": "5542",
    "kommunenavn": "Skjervøy",
    "slug": "skjervoy",
    "total": 61,
    "band": "OK",
    "centerNote": "Kommunesentrum",
    "population": 0,
    "fylkesnavn": "Troms",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Innenfor 2 aktsomhetsområder",
        "score": 20
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Troms",
        "score": 54
      }
    }
  },
  {
    "rank": 9,
    "kommunenummer": "4647",
    "kommunenavn": "Sunnfjord",
    "slug": "sunnfjord",
    "total": 62,
    "band": "OK",
    "centerNote": "Førde",
    "population": 22804,
    "fylkesnavn": "Sogn og Fjordane",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Innenfor 2 aktsomhetsområder",
        "score": 20
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Sogn og Fjordane",
        "score": 60
      }
    }
  },
  {
    "rank": 10,
    "kommunenummer": "1557",
    "kommunenavn": "Gjemnes",
    "slug": "gjemnes",
    "total": 62,
    "band": "OK",
    "centerNote": "Kommunesentrum",
    "population": 0,
    "fylkesnavn": "Møre og Romsdal",
    "components": {
      "flood": {
        "value": "Moderat",
        "score": 40
      },
      "quickClay": {
        "value": "Utenfor",
        "score": 100
      },
      "skred": {
        "value": "Innenfor 2 aktsomhetsområder",
        "score": 20
      },
      "stormSurge": {
        "value": "Utenfor",
        "score": 100
      },
      "radon": {
        "value": "Ikke vurdert",
        "score": null,
        "assessed": false
      },
      "klimaprofil": {
        "value": "Møre og Romsdal",
        "score": 60
      }
    }
  }
],
  comparisons: [
  {
    "pairId": "oslo-bergen",
    "title": "Oslo vs. Bergen",
    "rationale": "Innland mot vestkyst — stormflo og høy nedbør drar Bergen ned, mens Oslo trekkes ned av høy radon.",
    "left": {
      "label": "Karl Johans gate, Oslo",
      "kommunenavn": "Oslo",
      "total": 87,
      "band": "Utmerket",
      "fylkesnavn": "Oslo og Akershus",
      "components": {
        "flood": {
          "value": "Lav",
          "score": 100
        },
        "quickClay": {
          "value": "Utenfor",
          "score": 100
        },
        "skred": {
          "value": "Utenfor",
          "score": 100
        },
        "stormSurge": {
          "value": "Utenfor",
          "score": 100
        },
        "radon": {
          "value": "Høy",
          "score": 20,
          "assessed": true
        },
        "klimaprofil": {
          "value": "Oslo og Akershus",
          "score": 64
        }
      }
    },
    "right": {
      "label": "Bryggen, Bergen",
      "kommunenavn": "Bergen",
      "total": 90,
      "band": "Utmerket",
      "fylkesnavn": "Hordaland",
      "components": {
        "flood": {
          "value": "Lav",
          "score": 100
        },
        "quickClay": {
          "value": "Utenfor",
          "score": 100
        },
        "skred": {
          "value": "Utenfor",
          "score": 100
        },
        "stormSurge": {
          "value": "Utenfor",
          "score": 100
        },
        "radon": {
          "value": "Moderat",
          "score": 60,
          "assessed": true
        },
        "klimaprofil": {
          "value": "Hordaland",
          "score": 60
        }
      }
    }
  },
  {
    "pairId": "stavanger-trondheim",
    "title": "Stavanger vs. Trondheim",
    "rationale": "To kystbyer — kvikkleirebåndet rundt Trondheimsfjorden vs. flomutsatte kanaler i Stavanger sentrum.",
    "left": {
      "label": "Stavanger sentrum",
      "kommunenavn": "Stavanger",
      "total": 94,
      "band": "Utmerket",
      "fylkesnavn": "Rogaland",
      "components": {
        "flood": {
          "value": "Lav",
          "score": 100
        },
        "quickClay": {
          "value": "Utenfor",
          "score": 100
        },
        "skred": {
          "value": "Utenfor",
          "score": 100
        },
        "stormSurge": {
          "value": "Utenfor",
          "score": 100
        },
        "radon": {
          "value": "Lav",
          "score": 100,
          "assessed": true
        },
        "klimaprofil": {
          "value": "Rogaland",
          "score": 58
        }
      }
    },
    "right": {
      "label": "Trondheim torg",
      "kommunenavn": "Trondheim",
      "total": 88,
      "band": "Utmerket",
      "fylkesnavn": "Trøndelag",
      "components": {
        "flood": {
          "value": "Lav",
          "score": 100
        },
        "quickClay": {
          "value": "Utenfor",
          "score": 100
        },
        "skred": {
          "value": "Utenfor",
          "score": 100
        },
        "stormSurge": {
          "value": "Utenfor",
          "score": 100
        },
        "radon": {
          "value": "Moderat",
          "score": 60,
          "assessed": true
        },
        "klimaprofil": {
          "value": "Trøndelag",
          "score": 48
        }
      }
    }
  },
  {
    "pairId": "kristiansand-tromso",
    "title": "Kristiansand vs. Tromsø",
    "rationale": "Sørlandskyst mot arktisk by — milde stormer kontra stigende permafrost-temperatur og snøskredfare.",
    "left": {
      "label": "Kvadraturen, Kristiansand",
      "kommunenavn": "Kristiansand",
      "total": 95,
      "band": "Utmerket",
      "fylkesnavn": "Agder",
      "components": {
        "flood": {
          "value": "Lav",
          "score": 100
        },
        "quickClay": {
          "value": "Utenfor",
          "score": 100
        },
        "skred": {
          "value": "Utenfor",
          "score": 100
        },
        "stormSurge": {
          "value": "Utenfor",
          "score": 100
        },
        "radon": {
          "value": "Lav",
          "score": 100,
          "assessed": true
        },
        "klimaprofil": {
          "value": "Agder",
          "score": 67
        }
      }
    },
    "right": {
      "label": "Tromsø sentrum",
      "kommunenavn": "Tromsø",
      "total": 93,
      "band": "Utmerket",
      "fylkesnavn": "Troms",
      "components": {
        "flood": {
          "value": "Lav",
          "score": 100
        },
        "quickClay": {
          "value": "Utenfor",
          "score": 100
        },
        "skred": {
          "value": "Utenfor",
          "score": 100
        },
        "stormSurge": {
          "value": "Utenfor",
          "score": 100
        },
        "radon": {
          "value": "Lav",
          "score": 100,
          "assessed": true
        },
        "klimaprofil": {
          "value": "Troms",
          "score": 54
        }
      }
    }
  },
  {
    "pairId": "flam-elverum",
    "title": "Flåm vs. Elverum",
    "rationale": "Fjordbygd under stupbratte fjellsider mot rolig innland — skred mot ingen-skred i samme tabell.",
    "left": {
      "label": "Flåm sentrum",
      "kommunenavn": "Aurland",
      "total": 27,
      "band": "Svært svak",
      "fylkesnavn": "Sogn og Fjordane",
      "components": {
        "flood": {
          "value": "Høy",
          "score": 0
        },
        "quickClay": {
          "value": "Faresone",
          "score": 0
        },
        "skred": {
          "value": "Innenfor 2 aktsomhetsområder",
          "score": 20
        },
        "stormSurge": {
          "value": "Ekstremtilfelle",
          "score": 70
        },
        "radon": {
          "value": "Ikke vurdert",
          "score": null,
          "assessed": false
        },
        "klimaprofil": {
          "value": "Sogn og Fjordane",
          "score": 60
        }
      }
    },
    "right": {
      "label": "Elverum sentrum",
      "kommunenavn": "Elverum",
      "total": 93,
      "band": "Utmerket",
      "fylkesnavn": "Hedmark",
      "components": {
        "flood": {
          "value": "Lav",
          "score": 100
        },
        "quickClay": {
          "value": "Utenfor",
          "score": 100
        },
        "skred": {
          "value": "Utenfor",
          "score": 100
        },
        "stormSurge": {
          "value": "Utenfor",
          "score": 100
        },
        "radon": {
          "value": "Ikke vurdert",
          "score": null,
          "assessed": false
        },
        "klimaprofil": {
          "value": "Hedmark",
          "score": 61
        }
      }
    }
  }
],
};
