/**
 * Pre-computed landing-page data for /pendlings-poeng.
 *
 * Regenerated by `scripts/refresh-pendlings-poeng-landing.ts`, which hits
 * Entur for each kommune candidate + comparison address and writes back two
 * ranked lists (the six work-center kommuner, and the top 10 pendler-kommuner
 * around them) plus all comparison results. The page reads this file at build
 * time; revalidates via ISR every 24 hours (page.tsx). Refresh the data file
 * weekly, or when thresholds/weights change.
 *
 * Ranking order within each list: total desc → population desc (from
 * kommune-population.ts) → doorToDoorMinutes asc. Population as the primary
 * tiebreaker reflects actual pendler-relevance (more pendlers live in larger
 * kommuner) so scores-of-100 sort by size, not by a 1-minute travel-time
 * accident.
 *
 * DO NOT edit manually — re-run the refresh script instead.
 */
import type { WorkCenterId } from "@/lib/scoring/work-centers";

export interface KommuneScoreRow {
  rank: number;
  kommunenummer: string;
  kommunenavn: string;
  slug: string;
  total: number;
  centerName: string;
  centerId: WorkCenterId;
  centerNote: string;
  doorToDoorMinutes: number;
  frequencyPerHour: number;
  monthlyPriceNok: number;
  rushHourTested: boolean;
  population: number;
}

export interface ComparisonRow {
  label: string;
  kommunenavn: string;
  total: number;
  centerName: string;
  centerId: WorkCenterId;
  context: string;
  doorToDoorMinutes: number;
  frequencyPerHour: number;
  monthlyPriceNok: number;
  rushHourTested: boolean;
}

export interface PendlingsPoengLandingData {
  generatedAt: string;
  /** The six work-center kommuner (Oslo, Bergen, Trondheim, Stavanger, Tromsø, Kristiansand), each scored against its own work-center. */
  workCenterKommuner: ReadonlyArray<KommuneScoreRow>;
  /** Top 10 kommuner excluding the six work-center cities. The real pendler-kommuner around the big city cores. */
  topPendlerKommuner: ReadonlyArray<KommuneScoreRow>;
  comparisons: ReadonlyArray<ComparisonRow>;
}

export const PENDLINGS_POENG_LANDING_DATA: PendlingsPoengLandingData = {
  generatedAt: "2026-04-22T09:34:33.160Z",
  workCenterKommuner: [
  {
    "rank": 1,
    "kommunenummer": "0301",
    "kommunenavn": "Oslo",
    "slug": "oslo",
    "total": 100,
    "centerName": "Oslo",
    "centerId": "oslo",
    "centerNote": "Karl Johans gate",
    "doorToDoorMinutes": 8,
    "frequencyPerHour": 12,
    "monthlyPriceNok": 805,
    "rushHourTested": true,
    "population": 728714
  },
  {
    "rank": 2,
    "kommunenummer": "5001",
    "kommunenavn": "Trondheim",
    "slug": "trondheim",
    "total": 100,
    "centerName": "Trondheim",
    "centerId": "trondheim",
    "centerNote": "Trondheim torg",
    "doorToDoorMinutes": 11,
    "frequencyPerHour": 10,
    "monthlyPriceNok": 959,
    "rushHourTested": true,
    "population": 218460
  },
  {
    "rank": 3,
    "kommunenummer": "4204",
    "kommunenavn": "Kristiansand",
    "slug": "kristiansand",
    "total": 100,
    "centerName": "Kristiansand",
    "centerId": "kristiansand",
    "centerNote": "Christian IV's gate",
    "doorToDoorMinutes": 7,
    "frequencyPerHour": 12,
    "monthlyPriceNok": 336,
    "rushHourTested": true,
    "population": 119287
  },
  {
    "rank": 4,
    "kommunenummer": "4601",
    "kommunenavn": "Bergen",
    "slug": "bergen",
    "total": 98,
    "centerName": "Bergen",
    "centerId": "bergen",
    "centerNote": "Bryggen",
    "doorToDoorMinutes": 5,
    "frequencyPerHour": 7,
    "monthlyPriceNok": 422,
    "rushHourTested": true,
    "population": 294860
  },
  {
    "rank": 5,
    "kommunenummer": "5501",
    "kommunenavn": "Tromsø",
    "slug": "tromso",
    "total": 98,
    "centerName": "Tromsø",
    "centerId": "tromso",
    "centerNote": "Tromsø storsenter",
    "doorToDoorMinutes": 9,
    "frequencyPerHour": 9.5,
    "monthlyPriceNok": 720,
    "rushHourTested": true,
    "population": 79943
  },
  {
    "rank": 6,
    "kommunenummer": "1103",
    "kommunenavn": "Stavanger",
    "slug": "stavanger",
    "total": 96,
    "centerName": "Stavanger/Sandnes",
    "centerId": "stavanger",
    "centerNote": "Pedersgata",
    "doorToDoorMinutes": 14,
    "frequencyPerHour": 16,
    "monthlyPriceNok": 300,
    "rushHourTested": true,
    "population": 151669
  }
],
  topPendlerKommuner: [
  {
    "rank": 1,
    "kommunenummer": "1108",
    "kommunenavn": "Sandnes",
    "slug": "sandnes",
    "total": 96,
    "centerName": "Stavanger/Sandnes",
    "centerId": "stavanger",
    "centerNote": "Sandnes stasjon",
    "doorToDoorMinutes": 26,
    "frequencyPerHour": 8.5,
    "monthlyPriceNok": 300,
    "rushHourTested": true,
    "population": 85785
  },
  {
    "rank": 2,
    "kommunenummer": "4627",
    "kommunenavn": "Askøy",
    "slug": "askoy",
    "total": 90,
    "centerName": "Bergen",
    "centerId": "bergen",
    "centerNote": "Kleppestø terminal",
    "doorToDoorMinutes": 29,
    "frequencyPerHour": 6.5,
    "monthlyPriceNok": 422,
    "rushHourTested": true,
    "population": 30600
  },
  {
    "rank": 3,
    "kommunenummer": "3205",
    "kommunenavn": "Lillestrøm",
    "slug": "lillestrom",
    "total": 86,
    "centerName": "Oslo",
    "centerId": "oslo",
    "centerNote": "Lillestrøm stasjon",
    "doorToDoorMinutes": 19,
    "frequencyPerHour": 4.5,
    "monthlyPriceNok": 1019,
    "rushHourTested": true,
    "population": 96771
  },
  {
    "rank": 4,
    "kommunenummer": "3222",
    "kommunenavn": "Lørenskog",
    "slug": "lorenskog",
    "total": 86,
    "centerName": "Oslo",
    "centerId": "oslo",
    "centerNote": "Lørenskog sentrum",
    "doorToDoorMinutes": 38,
    "frequencyPerHour": 13.5,
    "monthlyPriceNok": 1019,
    "rushHourTested": true,
    "population": 51511
  },
  {
    "rank": 5,
    "kommunenummer": "3207",
    "kommunenavn": "Nordre Follo",
    "slug": "nordre-follo",
    "total": 84,
    "centerName": "Oslo",
    "centerId": "oslo",
    "centerNote": "Ski stasjon",
    "doorToDoorMinutes": 18,
    "frequencyPerHour": 3,
    "monthlyPriceNok": 1233,
    "rushHourTested": true,
    "population": 65381
  },
  {
    "rank": 6,
    "kommunenummer": "3201",
    "kommunenavn": "Bærum",
    "slug": "baerum",
    "total": 81,
    "centerName": "Oslo",
    "centerId": "oslo",
    "centerNote": "Sandvika stasjon",
    "doorToDoorMinutes": 21,
    "frequencyPerHour": 2,
    "monthlyPriceNok": 1019,
    "rushHourTested": true,
    "population": 133228
  },
  {
    "rank": 7,
    "kommunenummer": "3218",
    "kommunenavn": "Ås",
    "slug": "aas",
    "total": 79,
    "centerName": "Oslo",
    "centerId": "oslo",
    "centerNote": "Ås stasjon",
    "doorToDoorMinutes": 28,
    "frequencyPerHour": 4,
    "monthlyPriceNok": 1233,
    "rushHourTested": true,
    "population": 22725
  },
  {
    "rank": 8,
    "kommunenummer": "5031",
    "kommunenavn": "Malvik",
    "slug": "malvik",
    "total": 78,
    "centerName": "Trondheim",
    "centerId": "trondheim",
    "centerNote": "Hommelvik sentrum",
    "doorToDoorMinutes": 38,
    "frequencyPerHour": 8,
    "monthlyPriceNok": 1200,
    "rushHourTested": true,
    "population": 14961
  },
  {
    "rank": 9,
    "kommunenummer": "5035",
    "kommunenavn": "Stjørdal",
    "slug": "stjordal",
    "total": 77,
    "centerName": "Trondheim",
    "centerId": "trondheim",
    "centerNote": "Stjørdal stasjon",
    "doorToDoorMinutes": 44,
    "frequencyPerHour": 6,
    "monthlyPriceNok": 1200,
    "rushHourTested": true,
    "population": 25108
  },
  {
    "rank": 10,
    "kommunenummer": "3216",
    "kommunenavn": "Vestby",
    "slug": "vestby",
    "total": 77,
    "centerName": "Oslo",
    "centerId": "oslo",
    "centerNote": "Vestby stasjon",
    "doorToDoorMinutes": 32,
    "frequencyPerHour": 4,
    "monthlyPriceNok": 1233,
    "rushHourTested": true,
    "population": 20167
  }
],
  comparisons: [
  {
    "label": "Karl Johans gate 1",
    "kommunenavn": "Oslo",
    "total": 100,
    "centerName": "Oslo",
    "centerId": "oslo",
    "context": "Oslo sentrum — tett kollektivnett med T-bane, trikk og tog.",
    "doorToDoorMinutes": 8,
    "frequencyPerHour": 12,
    "monthlyPriceNok": 805,
    "rushHourTested": true
  },
  {
    "label": "Bryggen, Bergen",
    "kommunenavn": "Bergen",
    "total": 98,
    "centerName": "Bergen",
    "centerId": "bergen",
    "context": "Bergen sentrum — Bybanen og bussrutebil sentralt.",
    "doorToDoorMinutes": 5,
    "frequencyPerHour": 7,
    "monthlyPriceNok": 422,
    "rushHourTested": true
  },
  {
    "label": "Pedersgata, Stavanger",
    "kommunenavn": "Stavanger",
    "total": 96,
    "centerName": "Stavanger/Sandnes",
    "centerId": "stavanger",
    "context": "Stavanger sentrum — nær Jærbanen og Kolumbus sine hovedruter.",
    "doorToDoorMinutes": 14,
    "frequencyPerHour": 16,
    "monthlyPriceNok": 300,
    "rushHourTested": true
  },
  {
    "label": "Drammen sentrum",
    "kommunenavn": "Drammen",
    "total": 56,
    "centerName": "Oslo",
    "centerId": "oslo",
    "context": "Togforbindelse til Oslo hvert 15. minutt i rush.",
    "doorToDoorMinutes": 43,
    "frequencyPerHour": 1,
    "monthlyPriceNok": 1447,
    "rushHourTested": true
  },
  {
    "label": "Geilo sentrum",
    "kommunenavn": "Hol",
    "total": 33,
    "centerName": "Oslo",
    "centerId": "oslo",
    "context": "Fjellbygd med få daglige avganger mot Oslo.",
    "doorToDoorMinutes": 238,
    "frequencyPerHour": 1,
    "monthlyPriceNok": 2000,
    "rushHourTested": false
  },
  {
    "label": "Voss sentrum",
    "kommunenavn": "Voss",
    "total": 42,
    "centerName": "Bergen",
    "centerId": "bergen",
    "context": "Ett tog i timen mot Bergen, ca. 80 minutters reise.",
    "doorToDoorMinutes": 94,
    "frequencyPerHour": 1.5,
    "monthlyPriceNok": 1200,
    "rushHourTested": true
  }
],
};
